language: node_js
node_js:
- '8.9.3'
sudo: false
cache:
  directories:
  - node_modules
install:
- yarn add codeclimate-test-reporter
script:
- npm run lint
- npm test
after_success:
- |
  codeclimate-test-reporter < coverage/lcov.info
